In [1]:
import pandas as pd
import numpy as np
credit_df = pd.read_csv("train.csv")

C:\Users\lokes\AppData\Local\Temp\ipykernel_9164\1391188640.py:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  credit_df = pd.read_csv("train.csv")

In [2]:
credit_df.columns

Index(['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [3]:
credit_df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [4]:
#drop unnecessary features
df = credit_df.drop(['ID', 'Customer_ID', 'Month', 'Name','Type_of_Loan','Credit_History_Age','SSN'],axis='columns')
df.head()

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,3,7,...,4.0,_,809.98,26.822620,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,-1,NaN,...,4.0,Good,809.98,31.944960,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,3,7,...,4.0,Good,809.98,28.609352,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,5,4,...,4.0,Good,809.98,31.377862,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,6,NaN,...,4.0,Good,809.98,24.797347,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [5]:
#Check for object data type columns
df.select_dtypes(include=['object']).columns

Index(['Age', 'Occupation', 'Annual_Income', 'Num_of_Loan',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Credit_Mix',
       'Outstanding_Debt', 'Payment_of_Min_Amount', 'Amount_invested_monthly',
       'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score'],
      dtype='object')

In [6]:
#let us convert non categorical object columns into numerical 
df['Age']=pd.to_numeric(df['Age'],errors='coerce')
df['Annual_Income']=pd.to_numeric(df['Annual_Income'],errors='coerce')
df['Num_of_Loan']=pd.to_numeric(df['Num_of_Loan'],errors='coerce')
df['Num_of_Delayed_Payment']=pd.to_numeric(df['Num_of_Delayed_Payment'],errors='coerce')
df['Changed_Credit_Limit']=pd.to_numeric(df['Changed_Credit_Limit'],errors='coerce')
df['Outstanding_Debt']=pd.to_numeric(df['Outstanding_Debt'],errors='coerce')
df['Amount_invested_monthly']=pd.to_numeric(df['Amount_invested_monthly'],errors='coerce')
df['Monthly_Balance']=pd.to_numeric(df['Monthly_Balance'],errors='coerce')

In [7]:
df.select_dtypes(include=['object']).columns

Index(['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour', 'Credit_Score'],
      dtype='object')

In [8]:
#convert invalid columns of age column into nan
df.loc[df['Age']<=0,'Age'] = np.nan
df[df['Age']<=0]

Empty DataFrame
Columns: [Age, Occupation, Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card, Interest_Rate, Num_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment, Changed_Credit_Limit, Num_Credit_Inquiries, Credit_Mix, Outstanding_Debt, Credit_Utilization_Ratio, Payment_of_Min_Amount, Total_EMI_per_month, Amount_invested_monthly, Payment_Behaviour, Monthly_Balance, Credit_Score]
Index: []

[0 rows x 21 columns]

In [9]:
#let us find missing values
df.isnull().sum()

Age                          5825
Occupation                      0
Annual_Income                6980
Monthly_Inhand_Salary       15002
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                  4785
Delay_from_due_date             0
Num_of_Delayed_Payment       9746
Changed_Credit_Limit         2091
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt             1009
Credit_Utilization_Ratio        0
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      8784
Payment_Behaviour               0
Monthly_Balance              1209
Credit_Score                    0
dtype: int64

In [10]:
# fill the missing values with median
df['Age']=df['Age'].fillna(df['Age'].median())
df['Annual_Income']=df['Annual_Income'].fillna(df['Annual_Income'].median())
df['Monthly_Inhand_Salary']=df['Monthly_Inhand_Salary'].fillna(df['Monthly_Inhand_Salary'].median())
df['Num_of_Loan']=df['Num_of_Loan'].fillna(df['Num_of_Loan'].median())
df['Num_of_Delayed_Payment']=df['Num_of_Delayed_Payment'].fillna(df['Num_of_Delayed_Payment'].median())
df['Changed_Credit_Limit']=df['Changed_Credit_Limit'].fillna(df['Changed_Credit_Limit'].median())
df['Num_Credit_Inquiries']=df['Num_Credit_Inquiries'].fillna(df['Num_Credit_Inquiries'].median())
df['Outstanding_Debt']=df['Outstanding_Debt'].fillna(df['Outstanding_Debt'].median())
df['Amount_invested_monthly']=df['Amount_invested_monthly'].fillna(df['Amount_invested_monthly'].median())
df['Monthly_Balance']=df['Monthly_Balance'].fillna(df['Monthly_Balance'].median())

In [11]:
df.isnull().sum()

Age                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [12]:
#Encoding categorical columns

In [13]:
from sklearn.preprocessing import LabelEncoder
le_Occupation = LabelEncoder()
le_Credit_Mix = LabelEncoder()
le_Payment_of_Min_Amount = LabelEncoder()
le_Payment_Behaviour = LabelEncoder()
le_Credit_Score = LabelEncoder()

In [14]:
df['Occupation_n']=le_Occupation.fit_transform(df['Occupation'])
df['Credit_Mix_n']=le_Credit_Mix.fit_transform(df['Credit_Mix'])
df['Payment_of_Min_Amount_n']=le_Payment_of_Min_Amount.fit_transform(df['Payment_of_Min_Amount'])
df['Payment_Behaviour_n']=le_Payment_Behaviour.fit_transform(df['Payment_Behaviour'])
df['Credit_Score_n']=le_Credit_Score.fit_transform(df['Credit_Score'])

In [15]:
df.head()

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Occupation_n,Credit_Mix_n,Payment_of_Min_Amount_n,Payment_Behaviour_n,Credit_Score_n
0,23.0,Scientist,19114.12,1824.843333,3,4,3,4.0,3,7.0,...,49.574949,80.415295,High_spent_Small_value_payments,312.494089,Good,12,3,1,3,0
1,23.0,Scientist,19114.12,3093.745000,3,4,3,4.0,-1,14.0,...,49.574949,118.280222,Low_spent_Large_value_payments,284.629162,Good,12,1,1,4,0
2,33.0,Scientist,19114.12,3093.745000,3,4,3,4.0,3,7.0,...,49.574949,81.699521,Low_spent_Medium_value_payments,331.209863,Good,12,1,1,5,0
3,23.0,Scientist,19114.12,3093.745000,3,4,3,4.0,5,4.0,...,49.574949,199.458074,Low_spent_Small_value_payments,223.451310,Good,12,1,1,6,0
4,23.0,Scientist,19114.12,1824.843333,3,4,3,4.0,6,14.0,...,49.574949,41.420153,High_spent_Medium_value_payments,341.489231,Good,12,1,1,2,0

In [16]:
#drop object categorical columns
df1 = df.drop(['Occupation','Credit_Mix','Payment_of_Min_Amount','Payment_Behaviour','Credit_Score'],axis='columns')
df1.head()

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,Outstanding_Debt,Credit_Utilization_Ratio,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Occupation_n,Credit_Mix_n,Payment_of_Min_Amount_n,Payment_Behaviour_n,Credit_Score_n
0,23.0,19114.12,1824.843333,3,4,3,4.0,3,7.0,11.27,...,809.98,26.822620,49.574949,80.415295,312.494089,12,3,1,3,0
1,23.0,19114.12,3093.745000,3,4,3,4.0,-1,14.0,11.27,...,809.98,31.944960,49.574949,118.280222,284.629162,12,1,1,4,0
2,33.0,19114.12,3093.745000,3,4,3,4.0,3,7.0,9.40,...,809.98,28.609352,49.574949,81.699521,331.209863,12,1,1,5,0
3,23.0,19114.12,3093.745000,3,4,3,4.0,5,4.0,6.27,...,809.98,31.377862,49.574949,199.458074,223.451310,12,1,1,6,0
4,23.0,19114.12,1824.843333,3,4,3,4.0,6,14.0,11.27,...,809.98,24.797347,49.574949,41.420153,341.489231,12,1,1,2,0

In [17]:
#split data into train and test datasets

In [18]:
from sklearn.model_selection import train_test_split
X = df1.drop(['Credit_Score_n'],axis='columns')
y = df1.Credit_Score_n
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [19]:
len(X_train)

70000

In [20]:
len(X_test)

30000

In [21]:
#Use Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()

In [23]:
lr_model.fit(X_train,y_train)

C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [24]:
lr_model.score(X_test,y_test)

0.5518333333333333

In [25]:
y_pred_lr = lr_model.predict(X_test)

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test,y_pred_lr))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      5322
           1       0.51      0.56      0.54      8805
           2       0.57      0.73      0.64     15873

    accuracy                           0.55     30000
   macro avg       0.36      0.43      0.39     30000
weighted avg       0.45      0.55      0.50     30000

C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [28]:
#Use Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()

In [30]:
dt_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [31]:
dt_model.score(X_test,y_test)

0.6670333333333334

In [32]:
y_pred_dt = dt_model.predict(X_test)

In [33]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.58      0.57      0.57      5322
           1       0.65      0.64      0.64      8805
           2       0.71      0.72      0.71     15873

    accuracy                           0.67     30000
   macro avg       0.64      0.64      0.64     30000
weighted avg       0.67      0.67      0.67     30000

In [34]:
#Use Random Forest

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()

In [36]:
rf_model.fit(X_train,y_train)

RandomForestClassifier()

In [37]:
rf_model.score(X_test,y_test)

0.7722

In [38]:
y_pred_rf = rf_model.predict(X_test)

In [39]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.71      0.70      0.70      5322
           1       0.78      0.77      0.77      8805
           2       0.79      0.80      0.79     15873

    accuracy                           0.77     30000
   macro avg       0.76      0.76      0.76     30000
weighted avg       0.77      0.77      0.77     30000

In [ ]:
#acheived maximum accuracy of 77% by using random forest algorithm